-- ==============================================================================
-- SCRIPT DDL SUPABASE - PROJETO VERSUSHUB
-- Cole este script no SQL Editor do painel do Supabase (https://supabase.com/dashboard)
-- ==============================================================================

-- 1. TABELA DE USUÁRIOS
CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    senha TEXT DEFAULT '',
    "dataNasc" TEXT,
    bio TEXT DEFAULT '',
    avatar TEXT DEFAULT '/image/boneco_logo_ofc.png',
    regiao TEXT DEFAULT 'Brasil',
    "jogosFavoritos" JSONB DEFAULT '[]'::jsonb,
    plataformas JSONB DEFAULT '[]'::jsonb,
    banner TEXT DEFAULT '',
    stats JSONB DEFAULT '{"disputed": 0, "won": 0, "wins": 0, "losses": 0}'::jsonb,
    conquistas JSONB DEFAULT '[{"titulo": "Perfil Ativado", "desc": "Configure e atualize suas conquistas para o ranking no painel de perfil.", "data": "Desbloqueado"}]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABELA DE TORNEIOS
CREATE TABLE IF NOT EXISTS public.torneios (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    jogo TEXT,
    data TEXT,
    status TEXT DEFAULT 'Inscrições abertas',
    "statusClass" TEXT DEFAULT 'status-aberto',
    banner TEXT,
    "criadorEmail" TEXT,
    descricao TEXT,
    categoria TEXT,
    plataforma TEXT,
    "inicioIso" TEXT,
    localizacao TEXT,
    modalidade TEXT DEFAULT 'online',
    regras TEXT,
    "taxaTipo" TEXT DEFAULT 'gratis',
    "taxaValor" TEXT DEFAULT '',
    "tipoPremio" TEXT DEFAULT 'nenhuma',
    premio1 TEXT DEFAULT '',
    premio2 TEXT DEFAULT '',
    premio3 TEXT DEFAULT '',
    "premiacaoExtra" TEXT DEFAULT '',
    requisitos TEXT DEFAULT '',
    link TEXT,
    "tipoInscricao" TEXT DEFAULT 'Solo ou Equipe',
    "maxIntegrantes" INTEGER DEFAULT 5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABELA DE EQUIPES
CREATE TABLE IF NOT EXISTS public.equipes (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    tag TEXT,
    jogos TEXT,
    plataforma TEXT,
    regiao TEXT,
    limite TEXT,
    sobre TEXT DEFAULT 'Nenhuma descrição informada.',
    logo TEXT DEFAULT '/image/logo.png',
    "leaderName" TEXT,
    "leaderAvatar" TEXT,
    "leaderEmail" TEXT,
    "torneiosGanhos" JSONB DEFAULT '[]'::jsonb,
    "torneiosAtuais" JSONB DEFAULT '[]'::jsonb,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABELA DE CURTIDAS (LIKES)
CREATE TABLE IF NOT EXISTS public.curtidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    torneio_id TEXT NOT NULL,
    user_email TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT curtidas_torneio_user_unique UNIQUE (torneio_id, user_email)
);

-- 5. TABELA DE INSCRIÇÕES
CREATE TABLE IF NOT EXISTS public.inscricoes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    torneio_id TEXT NOT NULL,
    user_email TEXT NOT NULL,
    tipo TEXT DEFAULT 'individual',
    id_participante TEXT,
    equipe_nome TEXT DEFAULT '',
    lineup JSONB DEFAULT '[]'::jsonb,
    status TEXT DEFAULT 'Pendente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT inscricoes_torneio_user_unique UNIQUE (torneio_id, user_email)
);

-- 6. TABELA DE MEMBROS DE EQUIPE
CREATE TABLE IF NOT EXISTS public.membros_equipe (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    equipe_id TEXT NOT NULL,
    user_email TEXT NOT NULL,
    status TEXT DEFAULT 'Pendente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT membros_equipe_user_unique UNIQUE (equipe_id, user_email)
);

-- Índices para otimização de consultas frequentes
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON public.usuarios(email);
CREATE INDEX IF NOT EXISTS idx_curtidas_torneio ON public.curtidas(torneio_id);
CREATE INDEX IF NOT EXISTS idx_curtidas_user ON public.curtidas(user_email);
CREATE INDEX IF NOT EXISTS idx_inscricoes_torneio ON public.inscricoes(torneio_id);
CREATE INDEX IF NOT EXISTS idx_inscricoes_user ON public.inscricoes(user_email);
CREATE INDEX IF NOT EXISTS idx_membros_equipe_id ON public.membros_equipe(equipe_id);
CREATE INDEX IF NOT EXISTS idx_membros_equipe_user ON public.membros_equipe(user_email);
CREATE INDEX IF NOT EXISTS idx_equipes_leader ON public.equipes("leaderEmail");
CREATE INDEX IF NOT EXISTS idx_torneios_criador ON public.torneios("criadorEmail");

-- ==============================================================================
-- POLÍTICAS DE ACESSO (Row Level Security - RLS)
-- ==============================================================================

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.torneios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curtidas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inscricoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membros_equipe ENABLE ROW LEVEL SECURITY;

-- Migrações seguras para tabelas pré-existentes
ALTER TABLE IF EXISTS public.usuarios ALTER COLUMN senha DROP NOT NULL;
ALTER TABLE IF EXISTS public.usuarios ALTER COLUMN senha SET DEFAULT '';
-- Purga qualquer senha antiga em texto puro
UPDATE public.usuarios SET senha = '' WHERE senha IS NOT NULL AND senha <> '';

ALTER TABLE IF EXISTS public.equipes ADD COLUMN IF NOT EXISTS "leaderId" UUID;
ALTER TABLE IF EXISTS public.membros_equipe ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE IF EXISTS public.torneios ADD COLUMN IF NOT EXISTS "tipoInscricao" TEXT DEFAULT 'Solo ou Equipe';
ALTER TABLE IF EXISTS public.torneios ADD COLUMN IF NOT EXISTS "maxIntegrantes" INTEGER DEFAULT 5;
ALTER TABLE IF EXISTS public.inscricoes ADD COLUMN IF NOT EXISTS equipe_nome TEXT DEFAULT '';
ALTER TABLE IF EXISTS public.inscricoes ADD COLUMN IF NOT EXISTS lineup JSONB DEFAULT '[]'::jsonb;

-- ------------------------------------------------------------------------------
-- 1. TABELA: usuarios
-- Leitura pública dos perfis, mas apenas o próprio usuário pode alterar ou excluir seu registro.
-- ------------------------------------------------------------------------------
DROP POLICY IF EXISTS "Acesso público usuarios" ON public.usuarios;
DROP POLICY IF EXISTS "Usuarios podem ser visualizados publicamente" ON public.usuarios;
CREATE POLICY "Usuarios podem ser visualizados publicamente" ON public.usuarios
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Usuarios podem criar seu proprio perfil" ON public.usuarios;
CREATE POLICY "Usuarios podem criar seu proprio perfil" ON public.usuarios
    FOR INSERT WITH CHECK (
        id = auth.uid() 
        OR lower(trim(email)) = lower(trim(auth.jwt() ->> 'email'))
        OR auth.role() = 'anon'
    );

-- UPDATE: Exige auth.uid() = id_usuario ou e-mail autenticado correspondente
DROP POLICY IF EXISTS "Usuarios so podem atualizar seu proprio perfil" ON public.usuarios;
CREATE POLICY "Usuarios so podem atualizar seu proprio perfil" ON public.usuarios
    FOR UPDATE USING (
        id = auth.uid() 
        OR lower(trim(email)) = lower(trim(auth.jwt() ->> 'email'))
    ) WITH CHECK (
        id = auth.uid() 
        OR lower(trim(email)) = lower(trim(auth.jwt() ->> 'email'))
    );

-- DELETE: Exige auth.uid() = id_usuario ou e-mail autenticado correspondente
DROP POLICY IF EXISTS "Usuarios so podem excluir seu proprio perfil" ON public.usuarios;
CREATE POLICY "Usuarios so podem excluir seu proprio perfil" ON public.usuarios
    FOR DELETE USING (
        id = auth.uid() 
        OR lower(trim(email)) = lower(trim(auth.jwt() ->> 'email'))
    );

-- ------------------------------------------------------------------------------
-- 2. TABELA: equipes
-- Leitura pública, mas apenas o líder pode editar ou excluir a equipe.
-- ------------------------------------------------------------------------------
DROP POLICY IF EXISTS "Acesso público equipes" ON public.equipes;
DROP POLICY IF EXISTS "Equipes podem ser visualizadas publicamente" ON public.equipes;
CREATE POLICY "Equipes podem ser visualizadas publicamente" ON public.equipes
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Usuarios autenticados podem criar equipes" ON public.equipes;
CREATE POLICY "Usuarios autenticados podem criar equipes" ON public.equipes
    FOR INSERT WITH CHECK (
        auth.role() = 'authenticated'
        OR "leaderId" = auth.uid()
        OR lower(trim("leaderEmail")) = lower(trim(auth.jwt() ->> 'email'))
        OR auth.role() = 'anon'
    );

-- UPDATE: Apenas o líder da equipe pode atualizar os dados
DROP POLICY IF EXISTS "Apenas o lider pode atualizar sua equipe" ON public.equipes;
CREATE POLICY "Apenas o lider pode atualizar sua equipe" ON public.equipes
    FOR UPDATE USING (
        "leaderId" = auth.uid()
        OR lower(trim("leaderEmail")) = lower(trim(auth.jwt() ->> 'email'))
    ) WITH CHECK (
        "leaderId" = auth.uid()
        OR lower(trim("leaderEmail")) = lower(trim(auth.jwt() ->> 'email'))
    );

-- DELETE: Apenas o líder da equipe pode excluir a equipe
DROP POLICY IF EXISTS "Apenas o lider pode excluir sua equipe" ON public.equipes;
CREATE POLICY "Apenas o lider pode excluir sua equipe" ON public.equipes
    FOR DELETE USING (
        "leaderId" = auth.uid()
        OR lower(trim("leaderEmail")) = lower(trim(auth.jwt() ->> 'email'))
    );

-- ------------------------------------------------------------------------------
-- 3. TABELA: membros_equipe
-- Leitura pública; alteração e exclusão exigem ser o próprio membro ou o líder da equipe.
-- ------------------------------------------------------------------------------
DROP POLICY IF EXISTS "Acesso público membros_equipe" ON public.membros_equipe;
DROP POLICY IF EXISTS "Membros de equipe podem ser visualizados publicamente" ON public.membros_equipe;
CREATE POLICY "Membros de equipe podem ser visualizados publicamente" ON public.membros_equipe
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Usuarios podem solicitar ou entrar em equipes" ON public.membros_equipe;
CREATE POLICY "Usuarios podem solicitar ou entrar em equipes" ON public.membros_equipe
    FOR INSERT WITH CHECK (
        user_id = auth.uid()
        OR lower(trim(user_email)) = lower(trim(auth.jwt() ->> 'email'))
        OR equipe_id IN (
            SELECT eq.id FROM public.equipes eq 
            WHERE eq."leaderId" = auth.uid() 
            OR lower(trim(eq."leaderEmail")) = lower(trim(auth.jwt() ->> 'email'))
        )
        OR auth.role() = 'anon'
    );

-- UPDATE: O próprio membro (para responder a convite) ou o líder da equipe (para aprovar/recusar)
DROP POLICY IF EXISTS "Membro ou lider pode atualizar solicitacao de membro" ON public.membros_equipe;
CREATE POLICY "Membro ou lider pode atualizar solicitacao de membro" ON public.membros_equipe
    FOR UPDATE USING (
        user_id = auth.uid()
        OR lower(trim(user_email)) = lower(trim(auth.jwt() ->> 'email'))
        OR equipe_id IN (
            SELECT eq.id FROM public.equipes eq 
            WHERE eq."leaderId" = auth.uid() 
            OR lower(trim(eq."leaderEmail")) = lower(trim(auth.jwt() ->> 'email'))
        )
    ) WITH CHECK (
        user_id = auth.uid()
        OR lower(trim(user_email)) = lower(trim(auth.jwt() ->> 'email'))
        OR equipe_id IN (
            SELECT eq.id FROM public.equipes eq 
            WHERE eq."leaderId" = auth.uid() 
            OR lower(trim(eq."leaderEmail")) = lower(trim(auth.jwt() ->> 'email'))
        )
    );

-- DELETE: O próprio membro (sair da equipe) ou o líder da equipe (remover/recusar membro)
DROP POLICY IF EXISTS "Membro ou lider pode remover registro de membro" ON public.membros_equipe;
CREATE POLICY "Membro ou lider pode remover registro de membro" ON public.membros_equipe
    FOR DELETE USING (
        user_id = auth.uid()
        OR lower(trim(user_email)) = lower(trim(auth.jwt() ->> 'email'))
        OR equipe_id IN (
            SELECT eq.id FROM public.equipes eq 
            WHERE eq."leaderId" = auth.uid() 
            OR lower(trim(eq."leaderEmail")) = lower(trim(auth.jwt() ->> 'email'))
        )
    );

-- ------------------------------------------------------------------------------
-- 4. TABELAS: torneios, curtidas, inscricoes
-- ------------------------------------------------------------------------------
DROP POLICY IF EXISTS "Acesso público torneios" ON public.torneios;
CREATE POLICY "Torneios podem ser visualizados publicamente" ON public.torneios
    FOR SELECT USING (true);
CREATE POLICY "Criador autenticado pode criar torneio" ON public.torneios
    FOR INSERT WITH CHECK (
        auth.role() = 'authenticated'
        OR lower(trim("criadorEmail")) = lower(trim(auth.jwt() ->> 'email'))
        OR auth.role() = 'anon'
    );
CREATE POLICY "Apenas o criador pode atualizar seu torneio" ON public.torneios
    FOR UPDATE USING (
        lower(trim("criadorEmail")) = lower(trim(auth.jwt() ->> 'email'))
    ) WITH CHECK (
        lower(trim("criadorEmail")) = lower(trim(auth.jwt() ->> 'email'))
    );
CREATE POLICY "Apenas o criador pode excluir seu torneio" ON public.torneios
    FOR DELETE USING (
        lower(trim("criadorEmail")) = lower(trim(auth.jwt() ->> 'email'))
    );

DROP POLICY IF EXISTS "Acesso público curtidas" ON public.curtidas;
CREATE POLICY "Curtidas podem ser visualizadas publicamente" ON public.curtidas
    FOR SELECT USING (true);
CREATE POLICY "Usuarios autenticados podem curtir" ON public.curtidas
    FOR INSERT WITH CHECK (
        lower(trim(user_email)) = lower(trim(auth.jwt() ->> 'email'))
        OR auth.role() = 'authenticated'
        OR auth.role() = 'anon'
    );
CREATE POLICY "Usuarios podem descurtir suas curtidas" ON public.curtidas
    FOR DELETE USING (
        lower(trim(user_email)) = lower(trim(auth.jwt() ->> 'email'))
    );

DROP POLICY IF EXISTS "Acesso público inscricoes" ON public.inscricoes;
CREATE POLICY "Inscricoes podem ser visualizadas publicamente" ON public.inscricoes
    FOR SELECT USING (true);
CREATE POLICY "Usuarios podem se inscrever" ON public.inscricoes
    FOR INSERT WITH CHECK (
        lower(trim(user_email)) = lower(trim(auth.jwt() ->> 'email'))
        OR auth.role() = 'authenticated'
        OR auth.role() = 'anon'
    );
CREATE POLICY "Participante ou organizador pode atualizar inscricao" ON public.inscricoes
    FOR UPDATE USING (
        lower(trim(user_email)) = lower(trim(auth.jwt() ->> 'email'))
        OR torneio_id IN (
            SELECT id FROM public.torneios
            WHERE lower(trim("criadorEmail")) = lower(trim(auth.jwt() ->> 'email'))
        )
    ) WITH CHECK (
        lower(trim(user_email)) = lower(trim(auth.jwt() ->> 'email'))
        OR torneio_id IN (
            SELECT id FROM public.torneios
            WHERE lower(trim("criadorEmail")) = lower(trim(auth.jwt() ->> 'email'))
        )
    );
CREATE POLICY "Participante ou organizador pode excluir inscricao" ON public.inscricoes
    FOR DELETE USING (
        lower(trim(user_email)) = lower(trim(auth.jwt() ->> 'email'))
        OR torneio_id IN (
            SELECT id FROM public.torneios
            WHERE lower(trim("criadorEmail")) = lower(trim(auth.jwt() ->> 'email'))
        )
    );

-- ------------------------------------------------------------------------------
-- 5. VIEW SEGURA PARA USUÁRIOS PÚBLICOS (NÃO EXPÕE A COLUNA SENHA)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.usuarios_publicos AS
SELECT 
    id,
    nome,
    email,
    "dataNasc",
    bio,
    avatar,
    regiao,
    "jogosFavoritos",
    plataformas,
    banner,
    stats,
    conquistas,
    created_at
FROM public.usuarios;

GRANT SELECT ON public.usuarios_publicos TO anon, authenticated;

-- ------------------------------------------------------------------------------
-- 6. VIEWS OTIMIZADAS PARA O RANKING (CÁLCULO DIRETO NO BANCO DE DADOS)
-- ------------------------------------------------------------------------------

-- 6.1 VIEW: Ranking de Jogadores (vw_ranking_jogadores)
CREATE OR REPLACE VIEW public.vw_ranking_jogadores AS
WITH player_teams AS (
    SELECT 
        lower(trim(m.user_email)) AS user_email,
        m.equipe_id
    FROM public.membros_equipe m
    WHERE m.status = 'Aceito'
    UNION
    SELECT 
        lower(trim(e."leaderEmail")) AS user_email,
        e.id AS equipe_id
    FROM public.equipes e
    WHERE e."leaderEmail" IS NOT NULL AND e."leaderEmail" <> ''
),
player_tournaments AS (
    SELECT 
        lower(trim(u.email)) AS user_email,
        COUNT(DISTINCT i.torneio_id) AS disputed
    FROM public.usuarios u
    LEFT JOIN (
        SELECT 
            i.torneio_id,
            lower(trim(i.user_email)) AS user_email,
            i.id_participante,
            lower(coalesce(i.tipo, 'individual')) AS tipo
        FROM public.inscricoes i
        WHERE i.status = 'Aceito'
    ) i ON (
        (i.tipo = 'individual' AND (i.user_email = lower(trim(u.email)) OR i.id_participante = lower(trim(u.email)) OR i.id_participante = u.id::text))
        OR (i.tipo = 'equipe' AND (i.id_participante IN (SELECT pt.equipe_id FROM player_teams pt WHERE pt.user_email = lower(trim(u.email))) OR i.user_email = lower(trim(u.email))))
    )
    GROUP BY lower(trim(u.email))
),
player_won_tournaments AS (
    SELECT 
        lower(trim(e."leaderEmail")) AS user_email,
        COALESCE(SUM(CASE WHEN jsonb_typeof(e."torneiosGanhos") = 'array' THEN jsonb_array_length(e."torneiosGanhos") ELSE 0 END), 0) AS won
    FROM public.equipes e
    WHERE e."leaderEmail" IS NOT NULL
    GROUP BY lower(trim(e."leaderEmail"))
),
player_computed AS (
    SELECT 
        u.id,
        u.nome,
        u.email,
        COALESCE(NULLIF(trim(u.avatar), ''), '/image/boneco_logo_ofc.png') AS avatar,
        ''::text AS tag,
        COALESCE(pt.disputed, 0)::int AS disputed,
        COALESCE(pw.won, 0)::int AS won,
        ((COALESCE(pw.won, 0) * 3) + GREATEST(0, COALESCE(pt.disputed, 0) - COALESCE(pw.won, 0)))::int AS wins,
        GREATEST(0, (COALESCE(pt.disputed, 0) * 2) - ((COALESCE(pw.won, 0) * 3) + GREATEST(0, COALESCE(pt.disputed, 0) - COALESCE(pw.won, 0))))::int AS losses
    FROM public.usuarios u
    LEFT JOIN player_tournaments pt ON lower(trim(u.email)) = pt.user_email
    LEFT JOIN player_won_tournaments pw ON lower(trim(u.email)) = pw.user_email
)
SELECT 
    id,
    nome,
    email,
    avatar,
    tag,
    disputed,
    won,
    wins,
    losses,
    GREATEST(0, (won * 300) + (wins * 15) + (disputed * 5) - (losses * 2))::int AS points,
    (CASE 
        WHEN (wins + losses) > 0 THEN ROUND((wins::numeric / (wins + losses)) * 100)
        WHEN disputed > 0 THEN 100
        ELSE 0
    END)::int AS win_rate,
    '/perfil/perfil-publico.html?id=' || COALESCE(id::text, email) AS link
FROM player_computed
ORDER BY points DESC, wins DESC, disputed DESC, nome ASC;

GRANT SELECT ON public.vw_ranking_jogadores TO anon, authenticated;

-- 6.2 VIEW: Ranking de Equipes (vw_ranking_equipes)
CREATE OR REPLACE VIEW public.vw_ranking_equipes AS
WITH team_tournaments AS (
    SELECT 
        e.id AS equipe_id,
        COUNT(DISTINCT i.torneio_id) AS inscricoes_count,
        COALESCE(CASE WHEN jsonb_typeof(e."torneiosGanhos") = 'array' THEN jsonb_array_length(e."torneiosGanhos") ELSE 0 END, 0) AS won_count
    FROM public.equipes e
    LEFT JOIN public.inscricoes i ON (
        (i.tipo = 'equipe' AND i.id_participante = e.id)
        OR i.id_participante = e.id
    ) AND i.status = 'Aceito'
    GROUP BY e.id, e."torneiosGanhos"
),
team_computed AS (
    SELECT 
        e.id,
        e.nome,
        COALESCE(e.tag, '') AS tag,
        COALESCE(NULLIF(trim(e.logo), ''), '/image/logo.png') AS logo,
        COALESCE(e.jogos, 'Multi-jogos') AS jogos,
        COALESCE(e."leaderName", 'Líder') AS "leaderName",
        COALESCE(e."leaderEmail", '') AS "leaderEmail",
        GREATEST(COALESCE(tt.inscricoes_count, 0), COALESCE(tt.won_count, 0))::int AS disputed,
        COALESCE(tt.won_count, 0)::int AS won,
        ((COALESCE(tt.won_count, 0) * 3) + GREATEST(0, GREATEST(COALESCE(tt.inscricoes_count, 0), COALESCE(tt.won_count, 0)) - COALESCE(tt.won_count, 0)))::int AS wins,
        GREATEST(0, (GREATEST(COALESCE(tt.inscricoes_count, 0), COALESCE(tt.won_count, 0)) * 2) - ((COALESCE(tt.won_count, 0) * 3) + GREATEST(0, GREATEST(COALESCE(tt.inscricoes_count, 0), COALESCE(tt.won_count, 0)) - COALESCE(tt.won_count, 0))))::int AS losses
    FROM public.equipes e
    LEFT JOIN team_tournaments tt ON e.id = tt.equipe_id
)
SELECT 
    id,
    nome,
    tag,
    logo,
    jogos,
    "leaderName",
    "leaderEmail",
    disputed,
    won,
    wins,
    losses,
    GREATEST(0, (won * 300) + (wins * 15) + (disputed * 5) - (losses * 2))::int AS points,
    (CASE 
        WHEN (wins + losses) > 0 THEN ROUND((wins::numeric / (wins + losses)) * 100)
        WHEN disputed > 0 THEN 100
        ELSE 0
    END)::int AS win_rate,
    '/equipes/template_equipe.html?id=' || id AS link
FROM team_computed
ORDER BY points DESC, won DESC, disputed DESC, nome ASC;

GRANT SELECT ON public.vw_ranking_equipes TO anon, authenticated;

-- ==============================================================================
-- SEED DATA: Usuários e Torneios para testes imediatos (SEM SENHAS EM TEXTO PURO)
-- ==============================================================================

INSERT INTO public.usuarios (nome, email, senha, "dataNasc", bio, avatar)
VALUES
    (
        'Caíque Brandão',
        'caique@gmail.com',
        '',
        '2008-01-01',
        'Opa me chamo Caíque, tenho 18 anos, amo jogos, principalmente Brawl Stars e Fortnite. Curto um bom Rock e amo uma resenha',
        '/equipes/images/caiquebrandao.jpg'
    ),
    (
        'zZ_Dinho_Winchexxter_Zz',
        'dinho@gmail.com',
        '',
        '1999-05-15',
        'Fala aí, eu sou o Dinho. Curto jogar FPS e participar de campeonatos on-line.',
        '/equipes/images/dinhowinches.jpg'
    ),
    (
        'Mar_cuzcuz',
        'marcuzcuz@gmail.com',
        '',
        '2000-11-20',
        'Eu sou o Marcuzcuz, gosto de Cuzcuz, galinhas e do Vasco.',
        '/equipes/images/marcuzcuz.jpg'
    )
ON CONFLICT (email) DO NOTHING;

INSERT INTO public.torneios (id, nome, jogo, data, status, "statusClass", banner, categoria, plataforma, link)
VALUES
    (
        'cerrado-cup',
        'Cerrado Cup CS:GO',
        'CS:GO',
        '22/03/2026',
        'Inscrições abertas',
        'status-aberto',
        '/images/cerradocup.jpg',
        'fps',
        'pc',
        '/torneio/detalhes-cerradocup.html'
    ),
    (
        'contra-cup',
        'Contra Cup Free Fire',
        'Free Fire',
        '01/03/2026',
        'Em andamento',
        'status-andamento',
        '/images/contracup.jpeg',
        'battle-royale',
        'mobile',
        '/torneio/custom.html?id=contra-cup'
    ),
    (
        'liga-ff',
        'Liga FF Brasil',
        'Free Fire',
        '29/02/2026',
        'Encerrado',
        'status-encerrado',
        '/images/liga-ff-brasil.jpeg',
        'battle-royale',
        'mobile',
        '/torneio/custom.html?id=liga-ff'
    ),
    (
        'fifa-global-series',
        'FIFA Global Series',
        'FIFA',
        '22/02/2026',
        'Inscrições abertas',
        'status-aberto',
        '/images/fifa23_globalseries.webp',
        'esportes',
        'console',
        '/torneio/detalhes-fifaglobalseries.html'
    ),
    (
        'gamescom-latam',
        'Gamescom Latam CS:GO',
        'CS:GO',
        '01/04/2026',
        'Inscrições abertas',
        'status-aberto',
        '/pagina_inicial/image/gamescom_latam.webp',
        'fps',
        'pc',
        '/torneio/custom.html?id=gamescom-latam'
    ),
    (
        'parana-startups',
        'Paraná Startups Challenge',
        'CS:GO',
        '15/03/2026',
        'Em andamento',
        'status-andamento',
        '/pagina_inicial/image/parana.jpg',
        'fps',
        'pc',
        '/torneio/custom.html?id=parana-startups'
    ),
    (
        'evo-csgo',
        'Evo Championship Series CS:GO',
        'CS:GO',
        '10/02/2026',
        'Encerrado',
        'status-encerrado',
        '/pagina_inicial/image/evolution-championship-series.jpg',
        'fps',
        'pc',
        '/torneio/custom.html?id=evo-csgo'
    ),
    (
        'evo-ff',
        'Evo Championship Series Free Fire',
        'Free Fire',
        '05/04/2026',
        'Inscrições abertas',
        'status-aberto',
        '/pagina_inicial/image/evoff.jpg',
        'battle-royale',
        'mobile',
        '/torneio/custom.html?id=evo-ff'
    ),
    (
        'copa-ff',
        'C.O.P.A - Free Fire',
        'Free Fire',
        '18/04/2026',
        'Inscrições abertas',
        'status-aberto',
        '/pagina_inicial/image/copaff.jpg',
        'battle-royale',
        'mobile',
        '/torneio/custom.html?id=copa-ff'
    )
ON CONFLICT (id) DO NOTHING;

-- SEED DAS EQUIPES INICIAIS
INSERT INTO public.equipes (id, nome, tag, jogos, plataforma, regiao, limite, sobre, logo, "leaderName", "leaderAvatar", link)
VALUES
    ('viltrumitas', 'Viltrumitas', 'VLT', 'Valorant', 'pc', 'BR', '6', 'Equipe competitiva de Valorant com foco em torneios de alto nível.', '/equipes/image/Viltrumitas.jpg', 'OmniMan', '/equipes/image/Viltrumitas.jpg', '/equipes/detalhes-viltrumitas.html'),
    ('the-caras', 'The Caras', 'CRS', 'CS2', 'pc', 'BR', '4', 'Time experiente de CS2 pronto para dominar as ligas.', '/equipes/image/the%20caras.png', 'Butcher', '/equipes/image/the%20caras.png', '/equipes/detalhes-thecaras.html'),
    ('the-jacksons', 'The Jacksons', 'JKS', 'Free Fire', 'mobile', 'BR', '10', 'Squad tático de Free Fire focado em rush e posicionamento.', '/equipes/image/jacksons.png', 'Jackson', '/equipes/image/jacksons.png', '/equipes/detalhes-thejacksons.html'),
    ('os-vagalumes', 'Os Vagalumes', 'VGL', 'Fortnite', 'console', 'BR', '5', 'Construção rápida e precisão cirúrgica no Fortnite.', '/equipes/image/vagalumes.png', 'Firefly', '/equipes/image/vagalumes.png', '/equipes/detalhes-vagalumes.html'),
    ('shadow-foxes', 'Shadow Foxes', 'SFX', 'Valorant', 'pc', 'BR', '6', 'Estratégia e furtividade nos mapas competitivos de Valorant.', '/equipes/image/shadow_foxes.png', 'Fox', '/equipes/image/shadow_foxes.png', '/equipes/detalhes-shadowfoxes.html'),
    ('sky-titans', 'Sky Titans', 'SKT', 'CS2', 'pc', 'BR', '5', 'Equipe de mira afiada e comunicação limpa no CS2.', '/equipes/image/sky_titans.png', 'Titan', '/equipes/image/sky_titans.png', '/equipes/detalhes-skytitans.html'),
    ('dark-wolves', 'Dark Wolves', 'DW', 'Free Fire', 'mobile', 'BR', '5', 'Alcateia implacável pronta para conquistar cada safe zone.', '/equipes/image/dark_wolves.png', 'Alpha', '/equipes/image/dark_wolves.png', '/equipes/detalhes-darkwolves.html'),
    ('royal-dragons', 'Royal Dragons', 'RDG', 'Valorant', 'pc', 'BR', '5', 'Domínio do mapa e execuções perfeitas no Valorant.', '/equipes/image/royal_dragons.png', 'Dragon', '/equipes/image/royal_dragons.png', '/equipes/detalhes-royaldragons.html'),
    ('red-vipers', 'Red Vipers', 'RVP', 'CS2', 'pc', 'BR', '5', 'Agressividade calculada e precisão nos confrontos diretos.', '/equipes/image/red_vipers.png', 'Viper', '/equipes/image/red_vipers.png', '/equipes/detalhes-redvipers.html'),
    ('storm-riders', 'Storm Riders', 'STR', 'Fortnite', 'console', 'BR', '5', 'Velocidade e controle da tempestade nas partidas de Fortnite.', '/equipes/image/storm_riders.png', 'Rider', '/equipes/image/storm_riders.png', '/equipes/detalhes-stormriders.html')
ON CONFLICT (id) DO NOTHING;

-- ==============================================================================
-- 7. VIEWS E FUNÇÕES RPC PARA CÁLCULO OFICIAL DO RANKING NO SUPABASE
-- Permite consultar ranking ordenado pelas inscrições aceitas e vitórias reais
-- ==============================================================================

-- VIEW 1: Ranking de Jogadores (Agregação por inscrições aceitas)
CREATE OR REPLACE VIEW public.vw_ranking_jogadores AS
SELECT 
    u.id,
    u.nome,
    u.email,
    u.avatar,
    u.regiao,
    COUNT(DISTINCT i.torneio_id) AS torneios_disputados,
    -- Vitórias estimadas por títulos de equipes que lidera
    COALESCE((
        SELECT COALESCE(SUM(jsonb_array_length(COALESCE(eq."torneiosGanhos", '[]'::jsonb))), 0)
        FROM public.equipes eq
        WHERE lower(trim(eq."leaderEmail")) = lower(trim(u.email)) 
           OR lower(trim(eq."leaderName")) = lower(trim(u.nome))
    ), 0) AS torneios_vencidos,
    -- Pontos computados: 300 pts por torneio ganho + 25 pts por participação confirmada
    (
        COUNT(DISTINCT i.torneio_id) * 25 + 
        COALESCE((
            SELECT COALESCE(SUM(jsonb_array_length(COALESCE(eq."torneiosGanhos", '[]'::jsonb))), 0)
            FROM public.equipes eq
            WHERE lower(trim(eq."leaderEmail")) = lower(trim(u.email)) 
               OR lower(trim(eq."leaderName")) = lower(trim(u.nome))
        ), 0) * 300
    ) AS pontos
FROM public.usuarios u
LEFT JOIN public.inscricoes i 
    ON (lower(trim(i.user_email)) = lower(trim(u.email)) 
        OR lower(trim(i.id_participante)) = lower(trim(u.email)) 
        OR i.id_participante = u.id::text) 
    AND i.status = 'Aceito'
GROUP BY u.id, u.nome, u.email, u.avatar, u.regiao
ORDER BY pontos DESC, torneios_disputados DESC, u.nome ASC;

-- VIEW 2: Ranking de Equipes (Agregação por inscrições aceitas da equipe)
CREATE OR REPLACE VIEW public.vw_ranking_equipes AS
SELECT 
    e.id,
    e.nome,
    e.tag,
    e.logo,
    e.jogos,
    e."leaderName",
    e."leaderEmail",
    COUNT(DISTINCT i.torneio_id) AS torneios_disputados,
    jsonb_array_length(COALESCE(e."torneiosGanhos", '[]'::jsonb)) AS torneios_vencidos,
    -- Pontos computados: 300 pts por torneio ganho + 25 pts por participação confirmada
    (
        COUNT(DISTINCT i.torneio_id) * 25 + 
        jsonb_array_length(COALESCE(e."torneiosGanhos", '[]'::jsonb)) * 300
    ) AS pontos
FROM public.equipes e
LEFT JOIN public.inscricoes i 
    ON (i.id_participante = e.id OR (lower(trim(i.tipo)) = 'equipe' AND i.id_participante = e.id)) 
    AND i.status = 'Aceito'
GROUP BY e.id, e.nome, e.tag, e.logo, e.jogos, e."leaderName", e."leaderEmail", e."torneiosGanhos"
ORDER BY pontos DESC, torneios_disputados DESC, e.nome ASC;

-- Permissões de leitura para as views
GRANT SELECT ON public.vw_ranking_jogadores TO anon, authenticated;
GRANT SELECT ON public.vw_ranking_equipes TO anon, authenticated;


